# This is a basic workflow to help you get started with Actions

name: Second Workflow

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Run a multi-line script
       run: |
          echo "First Output"
          echo  "Second Output"
          echo  "Third Output "
